module.exports = {
    "pages": [
        "Consolas.png"
    ],
    "chars": [
        {
            "id": 124,
            "index": 374,
            "char": "|",
            "width": 5,
            "height": 22,
            "xoffset": 2,
            "yoffset": 1.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 0,
            "y": 0,
            "page": 0
        },
        {
            "id": 40,
            "index": 383,
            "char": "(",
            "width": 9,
            "height": 21,
            "xoffset": 1,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 6,
            "y": 0,
            "page": 0
        },
        {
            "id": 41,
            "index": 384,
            "char": ")",
            "width": 9,
            "height": 21,
            "xoffset": 0,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 16,
            "y": 0,
            "page": 0
        },
        {
            "id": 64,
            "index": 594,
            "char": "@",
            "width": 14,
            "height": 20,
            "xoffset": -2,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 26,
            "y": 0,
            "page": 0
        },
        {
            "id": 91,
            "index": 387,
            "char": "[",
            "width": 8,
            "height": 20,
            "xoffset": 1,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 41,
            "y": 0,
            "page": 0
        },
        {
            "id": 93,
            "index": 388,
            "char": "]",
            "width": 8,
            "height": 20,
            "xoffset": 1,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 50,
            "y": 0,
            "page": 0
        },
        {
            "id": 106,
            "index": 140,
            "char": "j",
            "width": 11,
            "height": 20,
            "xoffset": -1,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 0,
            "y": 23,
            "page": 0
        },
        {
            "id": 123,
            "index": 391,
            "char": "{",
            "width": 10,
            "height": 20,
            "xoffset": -1,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 0,
            "y": 44,
            "page": 0
        },
        {
            "id": 125,
            "index": 392,
            "char": "}",
            "width": 10,
            "height": 20,
            "xoffset": 0,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 11,
            "y": 44,
            "page": 0
        },
        {
            "id": 36,
            "index": 603,
            "char": "$",
            "width": 12,
            "height": 19,
            "xoffset": -1,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 12,
            "y": 22,
            "page": 0
        },
        {
            "id": 81,
            "index": 20,
            "char": "Q",
            "width": 13,
            "height": 19,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 22,
            "y": 42,
            "page": 0
        },
        {
            "id": 47,
            "index": 373,
            "char": "/",
            "width": 11,
            "height": 18,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 25,
            "y": 22,
            "page": 0
        },
        {
            "id": 92,
            "index": 590,
            "char": "\\",
            "width": 11,
            "height": 18,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 36,
            "y": 41,
            "page": 0
        },
        {
            "id": 33,
            "index": 352,
            "char": "!",
            "width": 6,
            "height": 17,
            "xoffset": 2,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 37,
            "y": 21,
            "page": 0
        },
        {
            "id": 37,
            "index": 681,
            "char": "%",
            "width": 14,
            "height": 17,
            "xoffset": -2,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 48,
            "y": 21,
            "page": 0
        },
        {
            "id": 63,
            "index": 355,
            "char": "?",
            "width": 9,
            "height": 17,
            "xoffset": 1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 48,
            "y": 39,
            "page": 0
        },
        {
            "id": 98,
            "index": 132,
            "char": "b",
            "width": 12,
            "height": 17,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 59,
            "y": 0,
            "page": 0
        },
        {
            "id": 100,
            "index": 134,
            "char": "d",
            "width": 11,
            "height": 17,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 58,
            "y": 39,
            "page": 0
        },
        {
            "id": 102,
            "index": 136,
            "char": "f",
            "width": 13,
            "height": 17,
            "xoffset": -2,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 63,
            "y": 18,
            "page": 0
        },
        {
            "id": 103,
            "index": 137,
            "char": "g",
            "width": 12,
            "height": 17,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 72,
            "y": 0,
            "page": 0
        },
        {
            "id": 105,
            "index": 139,
            "char": "i",
            "width": 11,
            "height": 17,
            "xoffset": 0,
            "yoffset": 2.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 70,
            "y": 36,
            "page": 0
        },
        {
            "id": 112,
            "index": 146,
            "char": "p",
            "width": 12,
            "height": 17,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 77,
            "y": 18,
            "page": 0
        },
        {
            "id": 113,
            "index": 147,
            "char": "q",
            "width": 11,
            "height": 17,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 85,
            "y": 0,
            "page": 0
        },
        {
            "id": 38,
            "index": 314,
            "char": "&",
            "width": 13,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 82,
            "y": 36,
            "page": 0
        },
        {
            "id": 48,
            "index": 613,
            "char": "0",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 90,
            "y": 18,
            "page": 0
        },
        {
            "id": 49,
            "index": 616,
            "char": "1",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 97,
            "y": 0,
            "page": 0
        },
        {
            "id": 50,
            "index": 617,
            "char": "2",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 110,
            "y": 0,
            "page": 0
        },
        {
            "id": 51,
            "index": 618,
            "char": "3",
            "width": 11,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 96,
            "y": 35,
            "page": 0
        },
        {
            "id": 53,
            "index": 620,
            "char": "5",
            "width": 11,
            "height": 16,
            "xoffset": 0,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 103,
            "y": 17,
            "page": 0
        },
        {
            "id": 54,
            "index": 621,
            "char": "6",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 115,
            "y": 17,
            "page": 0
        },
        {
            "id": 56,
            "index": 623,
            "char": "8",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 108,
            "y": 34,
            "page": 0
        },
        {
            "id": 57,
            "index": 624,
            "char": "9",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 108,
            "y": 51,
            "page": 0
        },
        {
            "id": 59,
            "index": 346,
            "char": ";",
            "width": 8,
            "height": 16,
            "xoffset": 0,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 96,
            "y": 52,
            "page": 0
        },
        {
            "id": 67,
            "index": 6,
            "char": "C",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 82,
            "y": 53,
            "page": 0
        },
        {
            "id": 71,
            "index": 10,
            "char": "G",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 105,
            "y": 68,
            "page": 0
        },
        {
            "id": 74,
            "index": 13,
            "char": "J",
            "width": 10,
            "height": 16,
            "xoffset": 0,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 118,
            "y": 68,
            "page": 0
        },
        {
            "id": 79,
            "index": 18,
            "char": "O",
            "width": 13,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 48,
            "y": 57,
            "page": 0
        },
        {
            "id": 83,
            "index": 22,
            "char": "S",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 62,
            "y": 57,
            "page": 0
        },
        {
            "id": 85,
            "index": 24,
            "char": "U",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 22,
            "y": 62,
            "page": 0
        },
        {
            "id": 104,
            "index": 138,
            "char": "h",
            "width": 11,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 36,
            "y": 60,
            "page": 0
        },
        {
            "id": 107,
            "index": 141,
            "char": "k",
            "width": 12,
            "height": 16,
            "xoffset": 0,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 0,
            "y": 65,
            "page": 0
        },
        {
            "id": 108,
            "index": 142,
            "char": "l",
            "width": 11,
            "height": 16,
            "xoffset": 0,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 75,
            "y": 70,
            "page": 0
        },
        {
            "id": 116,
            "index": 150,
            "char": "t",
            "width": 12,
            "height": 16,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 87,
            "y": 70,
            "page": 0
        },
        {
            "id": 121,
            "index": 155,
            "char": "y",
            "width": 13,
            "height": 16,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 48,
            "y": 74,
            "page": 0
        },
        {
            "id": 35,
            "index": 612,
            "char": "#",
            "width": 13,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 100,
            "y": 85,
            "page": 0
        },
        {
            "id": 52,
            "index": 619,
            "char": "4",
            "width": 13,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 114,
            "y": 85,
            "page": 0
        },
        {
            "id": 55,
            "index": 622,
            "char": "7",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 35,
            "y": 77,
            "page": 0
        },
        {
            "id": 65,
            "index": 4,
            "char": "A",
            "width": 14,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 13,
            "y": 79,
            "page": 0
        },
        {
            "id": 66,
            "index": 5,
            "char": "B",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 62,
            "y": 74,
            "page": 0
        },
        {
            "id": 68,
            "index": 7,
            "char": "D",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 0,
            "y": 82,
            "page": 0
        },
        {
            "id": 69,
            "index": 8,
            "char": "E",
            "width": 11,
            "height": 15,
            "xoffset": 0,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 0,
            "y": 101,
            "page": 0
        },
        {
            "id": 70,
            "index": 9,
            "char": "F",
            "width": 10,
            "height": 15,
            "xoffset": 0,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 12,
            "y": 101,
            "page": 0
        },
        {
            "id": 72,
            "index": 11,
            "char": "H",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 75,
            "y": 87,
            "page": 0
        },
        {
            "id": 73,
            "index": 12,
            "char": "I",
            "width": 11,
            "height": 15,
            "xoffset": 0,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 88,
            "y": 87,
            "page": 0
        },
        {
            "id": 75,
            "index": 14,
            "char": "K",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 62,
            "y": 90,
            "page": 0
        },
        {
            "id": 76,
            "index": 15,
            "char": "L",
            "width": 11,
            "height": 15,
            "xoffset": 0,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 48,
            "y": 91,
            "page": 0
        },
        {
            "id": 77,
            "index": 16,
            "char": "M",
            "width": 13,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 28,
            "y": 93,
            "page": 0
        },
        {
            "id": 78,
            "index": 17,
            "char": "N",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 23,
            "y": 109,
            "page": 0
        },
        {
            "id": 80,
            "index": 19,
            "char": "P",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 36,
            "y": 109,
            "page": 0
        },
        {
            "id": 82,
            "index": 21,
            "char": "R",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 49,
            "y": 107,
            "page": 0
        },
        {
            "id": 84,
            "index": 23,
            "char": "T",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 62,
            "y": 106,
            "page": 0
        },
        {
            "id": 86,
            "index": 25,
            "char": "V",
            "width": 14,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 75,
            "y": 103,
            "page": 0
        },
        {
            "id": 87,
            "index": 26,
            "char": "W",
            "width": 13,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 90,
            "y": 103,
            "page": 0
        },
        {
            "id": 88,
            "index": 27,
            "char": "X",
            "width": 14,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 104,
            "y": 101,
            "page": 0
        },
        {
            "id": 89,
            "index": 28,
            "char": "Y",
            "width": 14,
            "height": 15,
            "xoffset": -2,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 123,
            "y": 0,
            "page": 0
        },
        {
            "id": 90,
            "index": 29,
            "char": "Z",
            "width": 12,
            "height": 15,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 119,
            "y": 101,
            "page": 0
        },
        {
            "id": 60,
            "index": 691,
            "char": "<",
            "width": 11,
            "height": 14,
            "xoffset": -1,
            "yoffset": 5.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 128,
            "y": 85,
            "page": 0
        },
        {
            "id": 62,
            "index": 692,
            "char": ">",
            "width": 11,
            "height": 14,
            "xoffset": 0,
            "yoffset": 5.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 132,
            "y": 100,
            "page": 0
        },
        {
            "id": 95,
            "index": 591,
            "char": "_",
            "width": 14,
            "height": 5,
            "xoffset": -2,
            "yoffset": 17.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 13,
            "y": 95,
            "page": 0
        },
        {
            "id": 58,
            "index": 347,
            "char": ":",
            "width": 7,
            "height": 13,
            "xoffset": 2,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 13,
            "y": 65,
            "page": 0
        },
        {
            "id": 97,
            "index": 131,
            "char": "a",
            "width": 11,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 132,
            "y": 115,
            "page": 0
        },
        {
            "id": 99,
            "index": 133,
            "char": "c",
            "width": 11,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 121,
            "y": 34,
            "page": 0
        },
        {
            "id": 101,
            "index": 135,
            "char": "e",
            "width": 12,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 128,
            "y": 16,
            "page": 0
        },
        {
            "id": 109,
            "index": 143,
            "char": "m",
            "width": 12,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 138,
            "y": 0,
            "page": 0
        },
        {
            "id": 110,
            "index": 144,
            "char": "n",
            "width": 11,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 121,
            "y": 48,
            "page": 0
        },
        {
            "id": 111,
            "index": 145,
            "char": "o",
            "width": 12,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 129,
            "y": 62,
            "page": 0
        },
        {
            "id": 114,
            "index": 148,
            "char": "r",
            "width": 11,
            "height": 13,
            "xoffset": 0,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 140,
            "y": 76,
            "page": 0
        },
        {
            "id": 115,
            "index": 149,
            "char": "s",
            "width": 11,
            "height": 13,
            "xoffset": 0,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 133,
            "y": 30,
            "page": 0
        },
        {
            "id": 117,
            "index": 151,
            "char": "u",
            "width": 11,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 141,
            "y": 14,
            "page": 0
        },
        {
            "id": 118,
            "index": 152,
            "char": "v",
            "width": 13,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 151,
            "y": 0,
            "page": 0
        },
        {
            "id": 119,
            "index": 153,
            "char": "w",
            "width": 13,
            "height": 13,
            "xoffset": -2,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 133,
            "y": 44,
            "page": 0
        },
        {
            "id": 120,
            "index": 154,
            "char": "x",
            "width": 13,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 145,
            "y": 28,
            "page": 0
        },
        {
            "id": 122,
            "index": 156,
            "char": "z",
            "width": 11,
            "height": 13,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 153,
            "y": 14,
            "page": 0
        },
        {
            "id": 126,
            "index": 588,
            "char": "~",
            "width": 13,
            "height": 8,
            "xoffset": -1,
            "yoffset": 8.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 75,
            "y": 119,
            "page": 0
        },
        {
            "id": 43,
            "index": 683,
            "char": "+",
            "width": 12,
            "height": 12,
            "xoffset": -1,
            "yoffset": 6.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 142,
            "y": 58,
            "page": 0
        },
        {
            "id": 61,
            "index": 688,
            "char": "=",
            "width": 12,
            "height": 8,
            "xoffset": -1,
            "yoffset": 8.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 140,
            "y": 90,
            "page": 0
        },
        {
            "id": 94,
            "index": 587,
            "char": "^",
            "width": 12,
            "height": 10,
            "xoffset": -1,
            "yoffset": 4.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 0,
            "y": 117,
            "page": 0
        },
        {
            "id": 42,
            "index": 395,
            "char": "*",
            "width": 11,
            "height": 11,
            "xoffset": -1,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 104,
            "y": 117,
            "page": 0
        },
        {
            "id": 44,
            "index": 345,
            "char": ",",
            "width": 8,
            "height": 10,
            "xoffset": 0,
            "yoffset": 12.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 13,
            "y": 117,
            "page": 0
        },
        {
            "id": 96,
            "index": 316,
            "char": "`",
            "width": 10,
            "height": 8,
            "xoffset": -2,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 129,
            "y": 76,
            "page": 0
        },
        {
            "id": 34,
            "index": 593,
            "char": "\"",
            "width": 9,
            "height": 8,
            "xoffset": 0,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 89,
            "y": 119,
            "page": 0
        },
        {
            "id": 45,
            "index": 350,
            "char": "-",
            "width": 9,
            "height": 5,
            "xoffset": 0,
            "yoffset": 9.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 49,
            "y": 123,
            "page": 0
        },
        {
            "id": 39,
            "index": 592,
            "char": "'",
            "width": 6,
            "height": 8,
            "xoffset": 2,
            "yoffset": 3.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 75,
            "y": 54,
            "page": 0
        },
        {
            "id": 46,
            "index": 348,
            "char": ".",
            "width": 7,
            "height": 7,
            "xoffset": 1,
            "yoffset": 12.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 116,
            "y": 117,
            "page": 0
        },
        {
            "id": 32,
            "index": 3,
            "char": " ",
            "width": 0,
            "height": 0,
            "xoffset": -2,
            "yoffset": 15.37,
            "xadvance": 9.9,
            "chnl": 15,
            "x": 6,
            "y": 22,
            "page": 0
        }
    ],
    "info": {
        "face": "Consolas",
        "size": 18,
        "bold": 0,
        "italic": 0,
        "charset": [
            " ",
            "!",
            "\"",
            "#",
            "$",
            "%",
            "&",
            "'",
            "(",
            ")",
            "*",
            "+",
            ",",
            "-",
            ".",
            "/",
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            ":",
            ";",
            "<",
            "=",
            ">",
            "?",
            "@",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "H",
            "I",
            "J",
            "K",
            "L",
            "M",
            "N",
            "O",
            "P",
            "Q",
            "R",
            "S",
            "T",
            "U",
            "V",
            "W",
            "X",
            "Y",
            "Z",
            "[",
            "\\",
            "]",
            "^",
            "_",
            "`",
            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",
            "{",
            "|",
            "}",
            "~"
        ],
        "unicode": 1,
        "stretchH": 100,
        "smooth": 1,
        "aa": 1,
        "padding": [
            2,
            2,
            2,
            2
        ],
        "spacing": [
            0,
            0
        ],
        "outline": 0
    },
    "common": {
        "lineHeight": 21.08,
        "base": 15.37,
        "scaleW": 256,
        "scaleH": 128,
        "pages": 1,
        "packed": 0,
        "alphaChnl": 0,
        "redChnl": 0,
        "greenChnl": 0,
        "blueChnl": 0
    },
    "distanceField": {
        "fieldType": "msdf",
        "distanceRange": 4
    },
    "kernings": []
}
